// <auto-generated />
using DALco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DALco.Migrations
{
    [DbContext(typeof(data_collection))]
    [Migration("20220620212105_U")]
    partial class U
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DALco.disease", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name_OF_disease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("diseases_table");
                });

            modelBuilder.Entity("DALco.disease_drug", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("diseaseId")
                        .HasColumnType("int");

                    b.Property<int>("drugId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("diseaseId");

                    b.HasIndex("drugId");

                    b.ToTable("disease_drug_table");
                });

            modelBuilder.Entity("DALco.drug", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Scientific_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("The_number_of_medicine")
                        .HasColumnType("int");

                    b.Property<string>("cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("how_to_use")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_caliber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_size")
                        .HasColumnType("int");

                    b.Property<string>("trade_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("drug_table");
                });

            modelBuilder.Entity("DALco.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("user_table");
                });

            modelBuilder.Entity("DALco.disease_drug", b =>
                {
                    b.HasOne("DALco.disease", "diseases")
                        .WithMany("disease_drugs")
                        .HasForeignKey("diseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALco.drug", "drugs")
                        .WithMany("disease_drugs")
                        .HasForeignKey("drugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("diseases");

                    b.Navigation("drugs");
                });

            modelBuilder.Entity("DALco.disease", b =>
                {
                    b.Navigation("disease_drugs");
                });

            modelBuilder.Entity("DALco.drug", b =>
                {
                    b.Navigation("disease_drugs");
                });
#pragma warning restore 612, 618
        }
    }
}
